language: minimal

env:
  matrix:
    - TEST_MODE=live
    - TEST_MODE=local

services:
  - docker

before_install: ./.travis.sh before_install
install: ./.travis.sh install

before_script: |
  export SUFFIX="$(cat /proc/sys/kernel/random/uuid)"
  export CI=true
  export BUILD_TARGET=runtime
  export DOCKER_TAG="$TRAVIS_TAG"

  if [[ "$TEST_MODE" = "live" ]]; then
    export REGISTRATION_CREDENTIALS="$GITHUB_AUTH_USERNAME:$GITHUB_AUTH_TOKEN"
    export LOKOLE_QUEUE_BROKER_SCHEME="azureservicebus"
    export LOKOLE_RESOURCE_SUFFIX="$SUFFIX"
    export APPINSIGHTS_INSTRUMENTATIONKEY="$SUFFIX"
    export AZURITE_ACCOUNT="$TEST_AZURE_STORAGE_ACCOUNT"
    export AZURITE_KEY="$TEST_AZURE_STORAGE_KEY"
    export AZURITE_HOST=""
    export AZURITE_SECURE="True"
  else
    export REGISTRATION_CREDENTIALS="admin:password"
    export LOKOLE_QUEUE_BROKER_SCHEME="amqp"
  fi

script: ./.travis.sh script
after_success: ./.travis.sh after_success
after_failure: ./.travis.sh after_failure
after_script: ./.travis.sh after_script

before_deploy: ./.travis.sh before_deploy
deploy:
  - provider: script
    skip-cleanup: true
    script: ./.travis.sh deploy
    on:  # yamllint disable rule:truthy
      repo: ascoderu/lokole
      tags: true
      condition: $TEST_MODE = local

  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: build
    on:  # yamllint disable rule:truthy
      repo: ascoderu/lokole
      tags: true
      condition: $TEST_MODE = local
