version: '3.4'

services:

  statuspage:
    command: ["npm", "start"]
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - node_modules:/app/opwen_statuspage/node_modules
      - ./opwen_statuspage:/app/opwen_statuspage

  api:
    command: ["/app/docker/docker-entrypoint-dev.sh", "/app/docker/app/run-gunicorn.sh"]
    volumes:
      - ./opwen_email_server:/app/opwen_email_server

  worker:
    command: ["/app/docker/docker-entrypoint-dev.sh", "/app/docker/app/run-celery.sh"]
    volumes:
      - ./opwen_email_server:/app/opwen_email_server

  webapp:
    volumes:
      - ./opwen_email_client:/app/opwen_email_client
      - ./opwen_email_server:/app/opwen_email_server

volumes:
  node_modules:
