version: '3.4'

services:

  flower:
    image: mher/flower:latest
    depends_on:
      - rabbitmq
    command: ["--address=0.0.0.0", "--port=5555", "--broker=amqp://${LOKOLE_EMAIL_SERVER_QUEUES_SAS_NAME}:${LOKOLE_EMAIL_SERVER_QUEUES_SAS_KEY}@rabbitmq"]
    ports:
      - ${FLOWER_PORT}:5555

  cloudbrowser:
    image: cwolff/django-cloud-browser:latest
    depends_on:
      - azurite
    environment:
      CLOUD_BROWSER_DATASTORE: "ApacheLibcloud"
      CLOUD_BROWSER_APACHE_LIBCLOUD_PROVIDER: "AZURE_BLOBS"
      CLOUD_BROWSER_APACHE_LIBCLOUD_ACCOUNT: "${AZURITE_ACCOUNT}"
      CLOUD_BROWSER_APACHE_LIBCLOUD_SECRET_KEY: "${AZURITE_KEY}"
      CLOUD_BROWSER_APACHE_LIBCLOUD_HOST: "azurite"
      CLOUD_BROWSER_APACHE_LIBCLOUD_PORT: "10000"
      CLOUD_BROWSER_APACHE_LIBCLOUD_SECURE: "${AZURITE_SECURE}"
    ports:
      - ${CLOUDBROWSER_PORT}:8000
