swagger: '2.0'

info:
  title: Lokole Cloudserver Email API.
  version: '0.1'

basePath: '/api/email/metrics'

paths:

  '/pending/{domain}':

    get:
      operationId: opwen_email_server.integration.connexion.metrics_pending
      summary: Check how many emails are pending for the client.
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/Domain'
      responses:
        200:
          description: The number of pending emails for the client.
          schema:
            $ref: '#/definitions/PendingEmailsMetric'
        403:
          description: The client does not belong to the user.
      security:
        - basic: []

  '/users/{domain}':

    get:
      operationId: opwen_email_server.integration.connexion.metrics_users
      summary: Check how many users are registered for the client.
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/Domain'
      responses:
        200:
          description: The number of users registered for the client.
          schema:
            $ref: '#/definitions/UsersMetric'
        403:
          description: The client does not belong to the user.
      security:
        - basic: []

securityDefinitions:
  basic:
    type: basic
    x-basicInfoFunc: opwen_email_server.integration.connexion.basic_auth

parameters:

  Domain:
    name: domain
    description: Domain of the Lokole client.
    in: path
    type: string
    required: true

definitions:

  PendingEmailsMetric:
    type: object
    properties:
      pending_emails:
        description: The number of pending emails.
        type: integer
    required:
      - pending_emails

  UsersMetric:
    type: object
    properties:
      users:
        description: The number of users.
        type: integer
    required:
      - users
