swagger: '2.0'

info:
  title: Lokole Cloudserver Email API.
  version: '0.1'

basePath: '/api/email/upload'

paths:

  '/{client_id}':

    post:
      operationId: opwen_email_server.integration.connexion.client_write
      summary: Endpoint where Lokole clients notify the server that they wish to send/upload some emails.
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/ClientId'
        - $ref: '#/parameters/UploadInfo'
      responses:
        200:
          description: The emails were successfully uploaded from the Lokole.
        403:
          description: Request from unregistered client.

parameters:

  ClientId:
    name: client_id
    description: Id of the Lokole client.
    in: path
    type: string
    required: true

  UploadInfo:
    name: upload_info
    description: The emails to be uploaded.
    in: body
    schema:
      $ref: '#/definitions/UploadInfo'
    required: true

definitions:

  UploadInfo:
    type: object
    properties:
      resource_id:
        description: Id of the resource containing the emails (gzip jsonl file).
        type: string
    required:
      - resource_id
