apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-cluster-issuer
spec:
  acme:
    server: {{ .Values.letsencrypt.url }}
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-tls-secret
    http01: {}
