apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-cluster-issuer
spec:
  acme:
    server: {{ .Values.letsencrypt.url }}
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-tls-secret
