apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: {{ .Release.Name }}-cluster-issuer
spec:
  tls:
  - hosts:
    - {{.Values.domain}}
    secretName: {{ .Release.Name }}-tls-secret
  rules:
  - host: {{.Values.domain}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-nginx
          servicePort: 8888
