apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-nginx
  name: {{ .Release.Name }}-nginx
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    app: {{ .Release.Name }}-nginx
status:
  loadBalancer: {}
