apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-webapp
  name: {{ .Release.Name }}-webapp
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-webapp
status:
  loadBalancer: {}
