apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-webapp
  name: {{ .Release.Name }}-webapp
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-webapp
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-webapp
    spec:
      containers:
      - name: webapp
        image: {{.Values.version.imageRegistry}}/opwenwebapp:{{.Values.version.dockerTag}}
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: WEBAPP_PORT
          value: "8080"
        - name: WEBAPP_WORKERS
          value: "{{.Values.server.webappWorkers}}"
        {{ include "opwen.environment.shared" . }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "200m"
      restartPolicy: Always
status: {}
